### PR TITLE
feat: expose ready promise in composable

### PR DESCRIPTION
**Pull request by omnichronous**
## About the changes

This PR comes from a use case where I need my analytics solution to always report the up-to-date state of my feature toggles. I know there are already events fired for `ready` and `update`, but the `start` method of the Unleash client already [returns a promise](https://github.com/Unleash/unleash-proxy-client-js/blob/main/src/index.ts#L303) and it's much simpler to use that. I just made a new composable that returns it.

Closes #

### Important files

It's all about `src/useUnleashClientReady.ts`.

## Discussion points

I haven't exposed the ready state in `src/FlagProvider.vue` - I hope that doesn't stop this PR from getting merged.

### CODE REVIEW

**Comment by nunogois** [comment]
Hi @omnichronous, thank you for opening the PR!
I'm trying to better understand your requirements. How is this different from using `const { flagsReady } = useFlagsStatus()`?

**Comment by omnichronous** [comment]
Hi @nunogois, basically I'm tracking an event similar to this one very early in the app's lifecycle (but it goes for any other event):

```ts
trackEvent('app-loaded', { prop1: true, prop2: 'something', features: {})
```

I need `features` to be the current state of Unleash toggles, i.e. to ensure Unleash is loaded and the flags are fetched. As far as I can see the only way to use `flagsReady` here would be to do something with loops / watchers / my own promise to emulate what `start()` already returns.

Ultimately I just need to be able to await `isEnabled` and `getVariant` while still using the same client instance and composables.

**Comment by andreas-unleash** [comment]
Hi @omnichronous ,
I need a couple of clarifications to try to help:
- Is there a specific reason that you cannot use @nunogois suggestion and track your event when you get flagsReady=true?
- Can you describe why you think this is needed for your use case

The reason I am asking is that generally speaking we like to keep our SDK's consistent - so if this is a useful, genuine need might be worth us adapting

**Comment by omnichronous** [comment]
@andreas-unleash I'm not sure what you have in mind when you say "track your event when you get flagsReady=true".

My use case is, I need to send the Unleash state in many different tracking events. Some of these events will be fired before Unleash is ready, some after. I need these events to
1. be triggered by user behavior
2. be sent in the same order they were triggered
3. contain the accurate Unleash state

The only way I can see to do that with `flagsReady` is this:
1. Create a promise
2. Set up a watcher on `flagsReady` which resolves the promise once the value becomes `true`
3. Await this promise in my analytics tracking method and then attach the Unleash state

And my reasoning is: why should I have to set up my own promise like this when Unleash already provides it as the return value of `start()`?

**Comment by nunogois** [comment]
Hi @omnichronous,

I think there might be a slight misunderstanding.
Whether the Unleash client is `ready` or has `started` are different concepts.
- You can start an Unleash client that will never be ready (e.g. unable to reach upstream)
- You can have a ready Unleash client that will never be started (e.g. Unleash client that has the feature flag configuration ready, i.e. bootstrap, but is not configured to autostart)

If you'd like to have access to the underlying client instance, its state and all of its toggles, this is already possible. If you'd like, you can defer its start and log exactly when it starts (refer to https://github.com/Unleash/proxy-client-vue#deferring-client-start).

Here's a Stackblitz showing some examples of what's possible: https://stackblitz.com/edit/vitejs-vite-rka15n?file=src%2FApp.vue,src%2Fcomponents%2FFeatureFlag.vue&terminal=dev

**Given these examples, do you identify anything that you are unable to accomplish?**

Besides, we're a bit wary of adding to the API here. It would represent a new composable to maintain and either a different aspect of this specific SDK, or something to add to all the other ones. If there's a real need for this, we should consider if perhaps it belongs in https://github.com/Unleash/unleash-proxy-client-js instead.

**Comment by FredrikOseberg** [comment]
@omnichronous Seems like we're talking a bit past each other. Maybe there are some missing pieces of understanding. I think Nunos comment above gives some important insight into how the unleash SDK works internally. 

Given the information we have now, I will close this PR. If we have misunderstood you, you have our deepest apologies. And you're welcome to open this again with new information. Thank you!

**Pull request closed without merging**
